import { useEffect, type ReactNode } from 'react'
import { Link } from 'react-router'
import ResourcesPageLayout from '@/react-app/components/ResourcesPageLayout'

const EFFECTIVE_DATE = 'August 18, 2026'
const LAST_UPDATED = 'August 18, 2026'

const GREAT_REVIEW = [
  'You were there. Reviews and ratings are about an event you personally attended — or genuinely tried to attend. If the show was cancelled at the door or oversold and you never got in, that’s a legitimate review of the experience. Say which it was.',
  'It’s your honest opinion. Loved it, hated it, left after two songs — say so and say why. Strong opinions are welcome. Made-up facts are not.',
  'It’s about the show. The set, the sound, the crowd, the sightlines, security, timing, getting in and out, whether it was worth the money.',
  'It’s yours. Your own words. Not a copy of someone else’s review, not an article, not text generated by a tool and passed off as your night.',
]

type Rule = {
  number: string
  title: string
  body: ReactNode
}

const PART_ONE: Rule[] = [
  {
    number: '1',
    title: 'You had to be there.',
    body: 'Only review shows you personally attended. Not what your friend told you. Not what you saw in a clip. Not a set you streamed. If you left early, say so — that’s a real review too.',
  },
  {
    number: '2',
    title: 'Be honest about your own experience.',
    body: 'Say what you thought and be specific: sound, sightlines, crowd, security, timing, setlist, the room. Don’t exaggerate what happened, and don’t describe an experience you didn’t have. Opinions are yours and can be harsh. Facts have to be facts.',
  },
  {
    number: '3',
    title: 'Nobody pays for stars — including you.',
    body: (
      <>
        <ul className="list-disc pl-5 space-y-2 mb-4">
          <li>
            Don’t accept money, tickets, guest list, drinks, merch, comps, discounts, or anything
            else in exchange for posting a review, changing a review, or deleting one.
          </li>
          <li>Don’t offer any of that to someone else to get a review.</li>
          <li>Don’t review a show to help or hurt someone you have a relationship with.</li>
        </ul>
        <p className="mb-4">
          You have a conflict of interest if you work for or own the venue, promoter, ticketing
          company, label, management, or PR agency involved; are the artist, in the band, or on
          the crew; are an immediate family member of any of those; are a competing venue,
          promoter, or artist; or were given anything of value connected to the show.
        </p>
        <p className="mb-4">
          If you have a conflict, you have two options. Don’t review the show, or disclose the
          relationship in the first line of the review — plainly, like “I work at this venue” or “I
          was on the guest list as the promoter’s guest.” We may still label or remove the review,
          but disclosed is always better than hidden. Undisclosed conflicts are the fastest way to
          lose your account.
        </p>
        <p className="mb-4">
          An incentive tied to what your review says is never OK, even disclosed. A venue or artist
          may ask people to leave an honest review. They may not reward the sentiment. Payment,
          comps, or perks conditioned — openly or by implication — on a review being positive (or
          negative) are prohibited here, and they are prohibited by the FTC’s Rule on the Use of
          Consumer Reviews and Testimonials, which has been in force since October 21, 2024.
        </p>
        <p>
          This applies to us, too. If anyone on the Feedback team — founders included — posts a
          review, that account carries a visible staff badge and it stays visible on every review
          they post. No exceptions. We do not write reviews to make Feedback look busier, and we
          never post fabricated or tool-generated reviews. The FTC’s rule reaches undisclosed
          reviews by an owner, officer, manager, employee, agent, or an immediate relative of any
          of those.
        </p>
      </>
    ),
  },
  {
    number: '4',
    title: 'One person, one account, your own words.',
    body: 'No fake accounts, no second accounts to boost your own reviews, no accounts run for someone else, no bought or traded followers, no follow-farming rings, no bots. Don’t post the same review on twenty different shows. Don’t copy someone else’s review or writing. Don’t paste in machine-generated text and pass it off as your night — if you weren’t there, no tool can fix that. Buying, selling, or trading reviews, ratings, follows, or other engagement signals is prohibited, and the FTC’s rule separately prohibits trafficking in fake social-media indicators.',
  },
  {
    number: '5',
    title: 'Don’t use reviews as a weapon.',
    body: 'Don’t post a review to retaliate, extort, or pressure. Don’t rate a show one star (or five) to settle a score or move an average. Don’t threaten a bad review — or offer a good one — to get a refund, an upgrade, or free entry. Ask for a refund like a person, through the venue.',
  },
]

const PART_TWO: Rule[] = [
  {
    number: '6',
    title: 'No harassment, threats, or hate.',
    body: 'No targeted harassment or pile-ons. No coordinating other people to do it for you. No threats of violence against anyone, including artists, staff, security, or other users — direct, indirect, or “just joking.” No hate speech or hateful conduct based on race, ethnicity, national origin, religion, sex, gender, gender identity, sexual orientation, disability, serious illness, age, immigration status, caste, or any other protected characteristic. No hate symbols or coded equivalents in reviews, photos, usernames, or bios. No sexual harassment. No block evasion.',
  },
  {
    number: '7',
    title: 'No doxxing, and no naming individual workers.',
    body: 'Don’t post anyone’s private information — home or work address, phone number, email, workplace, financial details, ID documents, or exact live location — including your own. Criticize the venue, the security operation, or the sound; don’t name or describe an individual bartender, usher, or security guard in a way that identifies them. Crowd shots at a public show are fine; zooming in to shame a stranger is not. If someone was assaulted or endangered, report it to us and to the police rather than posting a name.',
  },
  {
    number: '8',
    title: 'No sexual content, and absolutely nothing involving minors.',
    body: (
      <>
        <p className="mb-4">
          No pornography or sexually explicit images or descriptions. No nudity, including implied
          nudity. No unwanted sexualization of anyone, including performers and other users.
          Content that sexualizes or endangers a minor — real, drawn, or machine-generated — is
          the one thing that gets an immediate, permanent ban with no appeal, and we report child
          sexual abuse material to the National Center for Missing & Exploited Children and to law
          enforcement. If you see it, report it and don’t share it, screenshot it, or quote it.
        </p>
        <p>
          Swearing is fine. This is live music. Describing a mosh pit is not violent content;
          wishing harm on a person is.
        </p>
      </>
    ),
  },
  {
    number: '9',
    title: 'Self-harm and crisis content.',
    body: 'Don’t encourage, instruct, or glorify suicide, self-harm, eating disorders, or dangerous drug use. If you’re struggling, we’d rather you talk to someone than post about it — in the US you can call or text 988 to reach the Suicide & Crisis Lifeline. If you see someone in danger, report the content and, if it’s urgent, call 911. We’ll surface support resources to the person, and we won’t punish someone for asking for help.',
  },
]

const PART_THREE: Rule[] = [
  {
    number: '10',
    title: 'No spam, no selling, no scams — especially ticket scams.',
    body: (
      <>
        <p className="mb-4">
          Feedback is not a marketplace. Do not use reviews, comments, profiles, or messages to:
        </p>
        <ul className="list-disc pl-5 space-y-2 mb-4">
          <li>
            Sell, resell, trade, or advertise tickets, wristbands, passes, or “spare +1s,” at any
            price, including face value.
          </li>
          <li>
            Post links to resale listings, payment handles, Cash App/Venmo/Zelle/crypto addresses,
            or DMs-for-tickets offers.
          </li>
          <li>Advertise a business, service, giveaway, or “follow for follow.”</li>
          <li>
            Post referral links, affiliate links, promo codes, phishing links, or bulk unsolicited
            messages.
          </li>
        </ul>
        <p className="mb-4">
          Why the flat ban on ticket sales: we can’t verify a stranger’s ticket, and a scammed fan
          is a scammed fan whether or not the seller meant it. Anyone offering tickets inside
          Feedback should be treated as a scammer and reported. We remove that content on sight,
          and repeat offenders lose their account on the first strike, not the third.
        </p>
        <p>
          Also prohibited: content promoting or facilitating illegal activity, drug sales, weapons,
          counterfeit merch, hacking, bootleg-recording sales, credential sharing, or evading a
          venue’s or a ticket seller’s rules.
        </p>
      </>
    ),
  },
  {
    number: '11',
    title: 'Photos and video: your shot, your night, your rights.',
    body: (
      <>
        <ul className="list-disc pl-5 space-y-2 mb-4">
          <li>
            Post only media you captured at the show you’re reviewing, or that you have permission
            to post.
          </li>
          <li>
            No screenshots or reposts of other people’s photos, press photos, promo images,
            watermarked shots, stock images, album art, or posters.
          </li>
          <li>
            No professional-length recordings or full sets — a clip of a moment you were part of
            is fine; a bootleg is not.
          </li>
          <li>
            No gratuitously violent or shocking imagery, and no screenshots of anyone’s private
            messages.
          </li>
          <li>
            Don’t post identifiable close-ups of other audience members or workers who clearly
            didn’t want to be filmed.
          </li>
          <li>
            No images of documents: no tickets with barcodes, no IDs, no receipts, no wristband QR
            codes.
          </li>
          <li>
            Respect the venue’s and the artist’s rules. Some shows ban photography or set a
            phone-free policy; if you were told not to shoot, don’t post it.
          </li>
          <li>
            We remove media that infringes someone’s copyright when we get a valid notice. Repeat
            infringers lose their accounts. See the copyright section of our Terms of Service.
          </li>
        </ul>
        <p>
          Note on location in photos: photos can carry hidden location data. Feedback strips
          location metadata from photos you upload before they’re published. Details are in our
          Privacy Policy.
        </p>
      </>
    ),
  },
  {
    number: '12',
    title: 'Impersonation.',
    body: 'Don’t pretend to be an artist, a venue, a promoter, a publication, a Feedback employee, or another user. You don’t have to use your real name — but a fan account has to say in its bio that it’s a fan account. Verified artist and venue accounts are marked; anyone else claiming to be one will be removed. Networks of accounts run to amplify content are removed.',
  },
  {
    number: '13',
    title: 'Stay on topic.',
    body: 'Reviews are about the show. Political and social commentary that isn’t about what happened at that show, rants about a venue’s employment practices or an artist’s personal life, and off-topic promotion belong somewhere else. If an artist said something on stage, reviewing how that landed in the room is on topic.',
  },
  {
    number: '14',
    title: 'Spoilers, if you care about them.',
    body: 'Setlist details in the first two lines of a review of a tour that’s still running are a courtesy question, not a rule. Use the “setlist spoiler” toggle if you’re getting granular. We may set it for you.',
  },
]

const LADDER = [
  {
    level: 'Warning (no strike)',
    trigger:
      'Borderline or first-time minor issue — off-topic review, unlabelled spoiler, tone in a comment',
    action: 'We remove or flag the content and tell you why. Nothing happens to your account.',
  },
  {
    level: 'Strike 1',
    trigger:
      'A clear violation of any rule — undisclosed conflict, unverifiable claim of attendance, spam, harassment',
    action: 'Content removed. Written notice naming the rule. Account stays active.',
  },
  {
    level: 'Strike 2',
    trigger: 'A second violation within 12 months',
    action:
      'Content removed. 7-day suspension: you can read Feedback but can’t post, comment, follow, or message.',
  },
  {
    level: 'Strike 3',
    trigger: 'A third violation within 12 months',
    action: 'Account suspended and reviews delisted. You can still request your data and appeal.',
  },
  {
    level: 'Immediate permanent ban (no strikes needed)',
    trigger:
      'Content sexualizing or endangering a minor; credible threats of violence; doxxing that puts someone at risk; ticket-sale scams and fraud; coordinated review manipulation, paid-review schemes, or selling followers; ban evasion',
    action:
      'Account terminated, content removed, and we report to law enforcement or NCMEC where required.',
  },
]

const TIMING = [
  {
    stage: 'Acknowledgement',
    commitment: 'Automatic confirmation the moment you submit a report',
  },
  {
    stage: 'First human review',
    commitment: 'Within 24 hours of the report',
  },
  {
    stage: 'Urgent categories (threats, minor safety, doxxing)',
    commitment: 'Prioritized ahead of the queue; usually within hours',
  },
  {
    stage: 'Outcome notice to the reporter',
    commitment:
      'When the review is complete — you’ll be told whether we acted, though not the details of another person’s account',
  },
  {
    stage: 'Notice to the person who posted',
    commitment: 'At the time we remove content or issue a strike, with the rule cited',
  },
]

function RuleCard({ rule }: { rule: Rule }) {
  return (
    <article className="glass-panel border border-white/10 rounded-xl p-5 sm:p-6">
      <p className="text-xs font-semibold uppercase tracking-wide text-momentum-flare mb-1">
        Rule {rule.number}
      </p>
      <h3 className="text-lg font-headline font-bold text-white mb-3">{rule.title}</h3>
      <div className="text-gray-300 leading-relaxed">{rule.body}</div>
    </article>
  )
}

function RuleList({ rules }: { rules: Rule[] }) {
  return (
    <div className="space-y-4">
      {rules.map((rule) => (
        <RuleCard key={rule.number} rule={rule} />
      ))}
    </div>
  )
}

export default function CommunityGuidelines() {
  useEffect(() => {
    document.title = 'Community Guidelines — Feedback'
    return () => {
      document.title = 'FEEDBACK - Where live music lives.'
    }
  }, [])

  return (
    <ResourcesPageLayout>
      <header className="text-center mb-14 sm:mb-16">
        <h1 className="fb-hero-title">Community Guidelines</h1>
        <p className="fb-section-subtitle fb-section-subtitle--center mt-4">
          Effective {EFFECTIVE_DATE}. Last updated {LAST_UPDATED}.
        </p>
      </header>

      <section className="mb-14 sm:mb-16 space-y-4 text-gray-300 leading-relaxed">
        <h2 className="fb-page-section-title mb-4">Why these exist</h2>
        <p>
          Feedback only works if the ratings are real. One person who was actually at the show,
          saying what it was actually like, is worth a thousand paid-for stars. Everything below
          protects that.
        </p>
        <p>
          These Guidelines are part of our Terms of Service. Using Feedback means agreeing to
          follow them. We enforce the spirit of these rules as well as the letter — if someone
          finds a new way to make Feedback worse, we’ll act on it and then write the rule down.
        </p>
        <p>
          We know people disagree about music. Disagreement is half the fun, and these rules are
          not about taste. They’re about honesty and safety.
        </p>
        <p>
          We’re a small team and real people read the reports. We respond to every report within 24
          hours.
        </p>
      </section>

      <section className="mb-14 sm:mb-16" aria-labelledby="great-review">
        <h2 id="great-review" className="fb-page-section-title mb-6">
          What makes a great Feedback review
        </h2>
        <ul className="space-y-3">
          {GREAT_REVIEW.map((item) => (
            <li
              key={item}
              className="glass-panel border border-white/10 rounded-xl p-4 sm:p-5 text-gray-300 leading-relaxed"
            >
              {item}
            </li>
          ))}
        </ul>
      </section>

      <section className="mb-14 sm:mb-16" aria-labelledby="part-one">
        <h2 id="part-one" className="fb-page-section-title mb-6">
          Part One — Reviews we can trust
        </h2>
        <RuleList rules={PART_ONE} />
      </section>

      <section className="mb-14 sm:mb-16" aria-labelledby="part-two">
        <h2 id="part-two" className="fb-page-section-title mb-6">
          Part Two — Respect the people here
        </h2>
        <RuleList rules={PART_TWO} />
      </section>

      <section className="mb-14 sm:mb-16" aria-labelledby="part-three">
        <h2 id="part-three" className="fb-page-section-title mb-6">
          Part Three — Keep it clean and keep it legal
        </h2>
        <RuleList rules={PART_THREE} />
      </section>

      <section className="mb-14 sm:mb-16" aria-labelledby="enforcement">
        <h2 id="enforcement" className="fb-page-section-title mb-6">
          What happens when a rule is broken
        </h2>
        <p className="text-gray-300 leading-relaxed mb-6">
          We use automated filtering plus human review. Objectionable content may be blocked at
          the moment of posting; anything reported gets human eyes. Most violations follow a
          three-strike model, with a fast lane for the worst content. A strike expires 12 months
          after it’s issued.
        </p>
        <div className="space-y-3 mb-6">
          {LADDER.map((row) => (
            <article
              key={row.level}
              className="glass-panel border border-white/10 rounded-xl p-5 sm:p-6"
            >
              <h3 className="font-headline font-bold text-white mb-2">{row.level}</h3>
              <p className="text-sm uppercase tracking-wide text-momentum-flare mb-2">
                What triggers it
              </p>
              <p className="text-gray-300 leading-relaxed mb-4">{row.trigger}</p>
              <p className="text-sm uppercase tracking-wide text-momentum-flare mb-2">What we do</p>
              <p className="text-gray-300 leading-relaxed">{row.action}</p>
            </article>
          ))}
        </div>
        <div className="space-y-4 text-gray-300 leading-relaxed">
          <p>
            Ban evasion resets nothing and extends everything. A new account made to dodge a
            suspension is removed, and the original suspension starts again.
          </p>
          <p>
            Other things we may do instead of, or alongside, a strike: remove a single review,
            remove a photo, hide a review from the rating average while keeping it visible, label a
            review as having an undisclosed relationship, remove a follower count obtained through
            manipulation, temporarily rate-limit posting, or restrict a venue or artist page.
          </p>
          <p>
            We never remove a review because someone with money asked us to. Venues, promoters,
            artists, labels, and PR firms can report content the same way you can, and we apply the
            same published rules to their reports as to yours. The same standards apply whether a
            review is glowing or brutal.
          </p>
          <p>
            A one-star review that follows these Guidelines stays up. This is a legal commitment as
            well as an editorial one: the FTC’s review rule prohibits using unfounded legal
            threats, intimidation, or other prohibited practices to suppress reviews, and requires
            that published review criteria be applied uniformly rather than suppressing reviews
            because of a negative rating or sentiment.
          </p>
          <p>
            We can and do remove content that is defamatory, harassing, abusive, obscene, sexually
            explicit, clearly fabricated, or that we reasonably believe is fake — and we apply those
            criteria to five-star reviews exactly as we apply them to one-star reviews.
          </p>
          <p>
            Venues, promoters, and artists: don’t intimidate reviewers. Using legal threats or
            harassment to get an honest negative review taken down breaks our rules, and the FTC’s
            review rule addresses it directly. Report the review instead and we’ll apply the rules.
            What we will always do: remove a review from someone who wasn’t there if you can show
            us why; remove or label a review from someone with an undisclosed conflict of interest;
            and remove fabricated factual claims, harassment, or doxxing.
          </p>
        </div>
      </section>

      <section className="mb-14 sm:mb-16 space-y-4 text-gray-300 leading-relaxed">
        <h2 className="fb-page-section-title mb-4">How to report something</h2>
        <p>
          In the app: tap the ··· menu on any review, comment, photo, or profile → Report → pick a
          reason. Reports are confidential; we never tell the person who reported them. Emergencies:
          if someone is in immediate danger, call 911 first, then report to us.
        </p>
        <p>
          Blocking works immediately and doesn’t require us. Blocking someone hides their content
          from you, hides yours from them, and stops them following or messaging you. You can see
          and undo blocks in Settings → Blocked accounts.
        </p>
      </section>

      <section className="mb-14 sm:mb-16" aria-labelledby="timing">
        <h2 id="timing" className="fb-page-section-title mb-6">
          What we promise on timing
        </h2>
        <div className="space-y-3">
          {TIMING.map((row) => (
            <article
              key={row.stage}
              className="glass-panel border border-white/10 rounded-xl p-5 sm:p-6"
            >
              <h3 className="font-headline font-bold text-white mb-2">{row.stage}</h3>
              <p className="text-gray-300 leading-relaxed">{row.commitment}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="mb-14 sm:mb-16 space-y-4 text-gray-300 leading-relaxed">
        <h2 className="fb-page-section-title mb-4">Appeals</h2>
        <p>
          Everyone gets one appeal per decision, and a person — not a filter — reads it. The person
          who reviews your appeal is not the person who made the original call.
        </p>
        <p>
          How: tap Appeal in the notice we sent you. When: within 30 days of the decision. What to
          include: what you think we got wrong. If it’s about attendance, anything showing you were
          there helps — a ticket, an order confirmation, a photo from your camera roll. Never send
          us a full ticket barcode; a redacted screenshot is enough. Timing: we acknowledge appeals
          within 24 hours and decide within 5 business days. Outcomes: decision reversed, with
          content restored and the strike removed; decision upheld with an explanation; or partly
          upheld — for example, content stays down but the strike is dropped. Exception: decisions
          involving content that sexualizes a minor are final and are not appealable.
        </p>
        <p>
          If your account is terminated you can still ask for a copy of your data or ask us to
          delete it — see our Privacy Policy.
        </p>
      </section>

      <section className="mb-14 sm:mb-16 space-y-4 text-gray-300 leading-relaxed">
        <h2 className="fb-page-section-title mb-4">Changes to these Guidelines</h2>
        <p>
          These Guidelines are a living document. When we change them we update the date at the
          top, and for significant changes we tell you in the app.
        </p>
      </section>

      <section className="border-t border-white/10 pt-10 space-y-6">
        <p className="text-gray-300 leading-relaxed text-center">
          We would rather have 500 real reviews than 50,000 fake ones. Thanks for keeping this
          honest. — The Feedback Team
        </p>
        <p className="text-center">
          <Link
            to="/how-it-works"
            className="text-momentum-flare hover:text-white transition-colors"
          >
            How Feedback works
          </Link>
        </p>
      </section>
    </ResourcesPageLayout>
  )
}
